### ISSUE TITLE
大佬这个b550暗黑+5950x能用吗？

### ISSUE THREAD

**Issue by AYUUUU293** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#10]

**Comment by AYUUUU293** [comment]
或者说需要改什么才能用

**Comment by ybakiame** [comment]
> 或者说需要改什么才能用

改patch中的cpu核心数，其他应该是通用的，具体情况得你自己尝试

**Comment by Jokin613** [comment]
那个是配置核心数的，昨天找了一下没找到

**Comment by AYUUUU293** [comment]
> > 或者说需要改什么才能用
> 
> 改patch中的cpu核心数，其他应该是通用的，具体情况得你自己尝试

那个是配置核心数的，昨天找了一下没找到

**Comment by ybakiame** [comment]
> > > 或者说需要改什么才能用
> > 
> > 
> > 改补丁中的cpu核心数，其他应该是通用的，具体情况得你自己试试
> 
> 那个是配置核心数的，昨天没找到

![截屏2021-09-15 15 30 17](https://user-images.githubusercontent.com/32604602/133390116-864b08b6-d72d-4c90-87ba-e1b05c865c9a.png)

**Comment by AYUUUU293** [comment]
> > > > 或者说需要改什么才能用
> > > 
> > > 
> > > 改补丁中的cpu核心数，其他应该是通用的，具体情况得你自己试试
> > 
> > 
> > 那个是配置核心数的，昨天没找到
> 
> ![截屏2021-09-15 15 30 17](https://user-images.githubusercontent.com/32604602/133390116-864b08b6-d72d-4c90-87ba-e1b05c865c9a.png)

好的，多谢

**Comment by ybakime** [comment]
> > > > > 或者说需要改什么才能用
> > > > 
> > > > 
> > > > 改补丁中的cpu核心数，其他应该是通用的，具体情况得你自己试试
> > > 
> > > 
> > > 那个是配置核心数的，昨天没找到
> > 
> > 
> > ![截屏2021-09-15 15 30 17](https://user-images.githubusercontent.com/32604602/133390116-864b08b6-d72d-4c90-87ba-e1b05c865c9a.png)
> 
> 好的，多谢

前面四条，每一条`Comment`后面有对应的macOS版本，你使用那个版本改那个版本的，或者全部一起改
