### ISSUE TITLE
感谢作者，这个EFI中没有USBMAP，我在附件中附上

### ISSUE THREAD

**Issue by destroyor** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#11]
受到15个PORT的限制，屏蔽了两个高速端口的usb 2.0的端口。
同时前置也屏蔽了一组前置USB2.0。
这个usbmap是在windows用UTBmap完成的，保证了蓝牙的开启。
[将附件的kext文件放入后，要在config文件中设置，同时要关闭kernel-quirks中的XhciPortLimit，选在false。
[Usbmap for  mag msi b550.zip](https://github.com/ybakiame/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI-EFI/files/7271871/Usbmap.for.mag.msi.b550.zip)

**Comment by ybakiame** [comment]
> 受到15个端口的限制，屏蔽了两个高速端口的usb 2.0的端口。 同时用的位置也屏蔽了一个端口的USB20。 这个usb在windows UTB地图完成的，保证了蓝牙的开启。 [将附件的kext文件设置动态后，要在config文件中，同时要关闭kernel-quirks中的XhciPortLimit，选在 [false。usbmap for mag msi b550.zip](https://github.com/ybakiame/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI-EFI/files/7271871/Usbmap.for.mag.msi.b550.zip)

> 1. 在使用过程中没有遇到过相关问题可以不必进行usb映射
> 2. 按照官方文档来说`usbMap`是适用于Intel的usb映射工具，amd还是更加倾向于手动进行映射
![截屏2021-10-05 13 45 20](https://user-images.githubusercontent.com/32604602/135968838-65fee192-973e-4b65-9cad-0c6083215f89.png)

**Comment by codedmart** [comment]
@ybakiame I don't understand how you have Bluetooth working without any usbmap? Everything seems to be working fine for me except bluetooth. It has worked 2 times, but not sure if reboots caused that or what. Do you know how I can fix this?
