### ISSUE TITLE
铭瑄b550m也是安装不了12beta3

### ISSUE THREAD

**Issue by wuwuwu223** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#13]

**Comment by wuwuwu223** [comment]
试过了包括第一版bios 可能因为第一版就支持5000系列cpu

**Comment by ybakiame** [comment]
> 过了试包括第一版bios 可能因为第一版就支持5000系列cpu

现在并没有看见有什么解决办法。如果没有能启动monterey的bios版本，建议回bigSur，等monterey正式发布后再看情况

**Comment by p2mmao** [comment]
我用7月份的BIOS 安装了12.0.1 处理器是5800X，但是有几个问题，详见：
https://bbs.pcbeta.com/viewthread-1909359-1-1.html

**Comment by ybakiame** [comment]
> 我用7月份的BIOS 安装了12.0.1 处理器是5800X，但是有几个问题，详见：
> https://bbs.pcbeta.com/viewthread-1909359-1-1.html

> 1. LucyRTL8125Ethernet.kext 至少在我使用Monterey beat版本期间是能正常工作的。
> 2. AirportItlwm.kext 在 Monterey上下需要下载BlueToolFixup.kext ，并禁用IntelBluetoothInjector.kext。[参考官方文档](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-does-this-kext-do)

**Comment by p2mmao** [comment]
没有用啊，该弄的都弄了，后来淘宝买了一个35块的USB wifi 可以上网了

**Comment by p2mmao** [comment]
我的5800X+ 微星B550M迫击炮WIFI的最新EFI ，OC 0705，还是搞不定12.0.1的WIFI，蓝牙和网卡，并且进入系统需要2-3次尝试

链接：https://pan.baidu.com/s/1VUgi_B_IW8bDUhBYtaW_TA 
提取码：u789

**Comment by p2mmao** [comment]
忘记说了，我是11.6升级安装，就是直接安装黑果小兵镜像里面的Monterey安装

**Comment by ybakiame** [comment]
> 忘记说了，我是11.6升级安装，就是直接安装黑果小兵镜像里面的Monterey安装

和你安装方式没有任何关系。

![截屏2021-11-07 下午4 58 29](https://user-images.githubusercontent.com/32604602/140638867-2eea5ca5-809c-475e-abb7-30e809610f62.png)

我使用`7C94v12`重新安装了Monterey，无线，板载网卡工作正常。
蓝牙请使用[1.1.3版本](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/1.1.3)
