### ISSUE TITLE
Moneterty为什么需要降低 BIOS版本

### ISSUE THREAD

**Issue by destroyor** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#15]
测试了一下，不需要降低bios版本啊，win11和macos 12.0.1都很正常啊

**Comment by destroyor** [comment]
bios版本7c94v194，为了麻烦，执行的是全新安装。之前直接升级确实有bug，不知道啥原因，而且intelbluetoothfirmware最高只能用到2.0版本，2.0.1有时会有冲突。
<img width="1920" alt="截屏2021-11-13 下午6 46 25" src="https://user-images.githubusercontent.com/32041656/141622102-dac7fc7c-c236-4316-acef-48b341adb000.png">
<img width="1135" alt="截屏2021-11-13 下午6 45 47" src="https://user-images.githubusercontent.com/32041656/141622217-cd9d8b0f-3e81-4bf9-bef8-34857e00bce9.png">
<img width="572" alt="截屏2021-11-13 下午6 46 36" src="https://user-images.githubusercontent.com/32041656/141622232-b1b51ee1-3dd6-4572-873f-e8fe7568dcdd.png">
<img width="584" alt="截屏2021-11-13 下午6 47 21" src="https://user-images.githubusercontent.com/32041656/141622247-b9a3057a-f632-454a-a07a-d8bde81e9084.png">

**Comment by ybakiame** [comment]
我这边的情况是，只有`7C94v12`及以下版本能启动Monterey，但是不能启动windows11。windows10可以启动但Wi-Fi，和板载网卡都无法使用，蓝牙安装驱动后可以正常驱动。可能和我显卡是刷的vibos有关系。根据你的硬件情况不同，请自行测试。

**Comment by destroyor** [comment]
我也刷了vbios，改成了uefi bios，是亮机卡7750。这个板子实际上是有bug的，经常掉蓝牙（macos和win11都一样），不影响启动，需要在bios中手动开关一下。

**Comment by p2mmao** [comment]
> 测试了一下，不需要降低bios版本啊，win11和macos 12.0.1都很正常啊

我这里是7月的BIOS，无论从11.6升级还是全新安装12.0.1 蓝牙 WIIF和2.5G有线网卡全部识别不出来，你是咋搞定的？

**Comment by Goooler** [comment]
我这里的状况是 Bios 升级到 7c94v194 可以启动安装器，但是磁盘工具里面识别不到 nvme 的固态

**Comment by lwj1994** [comment]
> 我也刷了vbios，改成了uefi bios，是亮机卡7750。这个板子实际上是有bug的，经常掉蓝牙（macos和win11都一样），不影响启动，需要在bios中手动开关一下。

不知道这个bug是硬件上的还是软件上的。挺糟心的，经常切到win的时候蓝牙没了

**Comment by destroyor** [comment]
可能是别的硬件问题吧，我把自己的OC文件放上来，你们愿意的可以试试，根据需要自己添加三码或是添加其他参数。
[OC.zip](https://github.com/ybakiame/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI-EFI/files/7562063/OC.zip)

**Comment by p2mmao** [comment]
> 可能是别的硬件问题吧，我把自己的OC文件放上来，你们愿意的可以试试，根据需要自己添加三码或是添加其他参数。 [OC.zip](https://github.com/ybakiame/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI-EFI/files/7562063/OC.zip)

用你的OC重新干净安装了一遍12.0.1，无线网卡，有线网卡和蓝牙还是出不来，有空把主板BIOS升级到最新版看看

**Comment by p2mmao** [comment]
BIOS已经升级到最新版，干净安装，无线网卡，有线网卡和蓝牙还是出不来  死心了：（

**Comment by Levonhard** [comment]
Finally after days trying, today I was able to pass through verbose boot to Monterey installation using destroyor OC, but now I'm facing a new problem, my HDD, SATA SSD and NVME are not showing, only my USB drive is showing in Disk Utility.
I realize also that during installation process, at least, only the 2 blue USB ports from rear are working, so in order to go to installation I have to put my usb drive in one of the ports and mouse to another.
I believe that wifi is not working too, since it's not showing the option to connect to wifi in the upper right side.
I'm using the 7C94v194 beta bios.
As I said I'm using destroyor OC with few changes to config.plist like added agdpmod=pikera boot arg since I have 6600xt, changed the processor type to 1537 and changed to 6 core into amd patch kernel since I have 5600x. So what can I do to get my HDD, SATA SSD and NVME to show into installation process?

**Comment by ybakiame** [comment]
> Finally after days trying, today I was able to pass through verbose boot to Monterey installation using destroyor OC, but now I'm facing a new problem, my HDD, SATA SSD and NVME are not showing, only my USB drive is showing in Disk Utility. I realize also that during installation process, at least, only the 2 blue USB ports from rear are working, so in order to go to installation I have to put my usb drive in one of the ports and mouse to another. I believe that wifi is not working too, since it's not showing the option to connect to wifi in the upper right side. I'm using the 7C94v194 beta bios. As I said I'm using destroyor OC with few changes to config.plist like added agdpmod=pikera boot arg since I have 6600xt, changed the processor type to 1537 and changed to 6 core into amd patch kernel since I have 5600x. So what can I do to get my HDD, SATA SSD and NVME to show into installation process?

May be related to MSI motherboard.

**Comment by destroyor** [comment]
After so many practices, I realized that MSI B550 mortor may have different  hardware edtions, and the USB  ports differ from one anther.
It is clear clear that B550 motherboards are not well-worked with Intel AX200/AX201 module , not only MSI  B550s report bugs, and not only in the Hackintosh area.

**Comment by destroyor** [comment]
one more thing:  in the installation process,  i use the intelbluetooth.kext of 1.1.3version， and replace it with 2.0 version in the post-installation.

**Comment by p2mmao** [comment]
> 

use paragon 17 in win10 to retore the mini image to  your partition you want to install Monterey
https://mega.nz/folder/vMMWGBrK#qMFm60btcoecRSysZPIS5Q

use this EFI to boot the OS:
https://mega.nz/file/aZU2DDbR#QcUVljqXIxXcnv1nDPQSaVE0ls-0IIewTulbKFcjYzU

**Comment by rclsmart** [comment]
我们组建了一个QQ群，经过我们的测试，发现 Bios 升级到 7c94v194 ，5000系列的处理器（5600/5800/5900/5950）无法进入安装，必须要BIOS关闭网卡芯片（WiFi，蓝牙，有线网卡）才能进安装（主板不带WiFi，蓝牙的芯片可以直接进安装），但是但是，进去没有硬盘，对没错就是找不到硬盘，sata，m2，都不行。
同时我们还发现，其他系列的cpu可以正常安装，（就是较老的处理器，比如楼上的1700，）比较新的都不行。目前不知道怎么解决了.

**Comment by Goooler** [comment]
@ybakiame 12.1 里面正常了？

**Comment by georgwacker** [comment]
I wonder what the differences are in ACPI that causes Monterey to fail and if we could potentially patch it.

Could someone with a 3xxx CPU post a complete DSDT/SSDT dump where Monterey is working? Perhaps on an earlier BIOS version as well? Please include the BIOS version in any case.

**Comment by Goooler** [comment]
Bios 更新了，试试新版行不行。

![image](https://user-images.githubusercontent.com/10363352/147477467-28fd78b4-f195-4c96-b8d6-38064235d9bb.png)

**Comment by Goooler** [comment]
我试过了，还是不行，绝望。

**Comment by destroyor** [comment]
实在要用  那就是pve虚拟机+显卡直通了

**Comment by LatteCat** [comment]
> 我们组建了一个QQ群，经过我们的测试，发现 Bios 升级到 7c94v194 ，5000系列的处理器（5600/5800/5900/5950）无法进入安装，必须要BIOS关闭网卡芯片（WiFi，蓝牙，有线网卡）才能进安装（主板不带WiFi，蓝牙的芯片可以直接进安装），但是但是，进去没有硬盘，对没错就是找不到硬盘，sata，m2，都不行。 同时我们还发现，其他系列的cpu可以正常安装，（就是较老的处理器，比如楼上的1700，）比较新的都不行。目前不知道怎么解决了.

我想加入 QQ 群，可以公布下群号么？
我的 5800x+MSI B550m wifi 安装和运行 Big Sur 11.6.4 都良好，但是启动 Monterey 11.2.1 就报 `still waiting for root device`，明明已经做了 USB 映射的
目前主板 bios 是 v19，试过降级 v12 之后，能重新进 bios，但是会出现显示器黑屏，无法进入系统的问题，无奈又换回了 v19

**Comment by Goooler** [comment]
弃坑吧，OSX 上面大佬都换到华硕了，我上个月直接换用 Ubuntu 了

**Comment by LatteCat** [comment]
那我还是咸鱼上买一个话说 B550M 吧，然后把微星的这个卖掉

**Comment by rclsmart** [comment]
![4 2~XPSDG WSPV~_@}@WJF8](https://user-images.githubusercontent.com/95858900/155139845-75fe4370-b3db-4bc8-8bca-74d827fd2b1e.png)
目前也不知道怎么解决

**Comment by LatteCat** [comment]
> ![4 2XPSDG WSPV_@}@WJF8](https://user-images.githubusercontent.com/95858900/155139845-75fe4370-b3db-4bc8-8bca-74d827fd2b1e.png) 目前也不知道怎么解决

按照给出的群号码搜不到该群，不知道是不是设置了权限
