### ISSUE TITLE
建议可以给仓库重命名一下，并加上话题

### ISSUE THREAD

**Issue by Goooler** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#19]
如题，可以参照 [这个仓库](https://github.com/portrayer/Hackintosh-Ryzen-MSI-B450I )，比如说可以命名成 `Hackintosh-Ryzen-MSI-B550M-MORTAR-WIFI`

![image](https://user-images.githubusercontent.com/10363352/148983757-ab4475cc-efc9-4f9b-8082-71ea79bcb74d.png)

**Comment by ybakiame** [comment]
ok
