### ISSUE TITLE
question

### ISSUE THREAD

**Issue by DobbyAkhmadi** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#21]
hi can i use this setting with ryzen 3700x asus b550A gaming gtx 760?

**Comment by ybakiame** [comment]
No, their hardware is different.You need to adjust it according to your hardware

**Comment by DobbyAkhmadi** [comment]
![WhatsApp Image 2022-04-01 at 4 50 50 PM](https://user-images.githubusercontent.com/7714857/161266096-398e6255-fbcc-47fa-b2cc-39ef2fbe847f.jpeg)

i have this issue what should i do for fix this issue?

**Comment by DobbyAkhmadi** [comment]
should i change the smbios? or graphic cards issue?

**Comment by ybakiame** [comment]
> should i change the smbios? or graphic cards issue?

Use `iMacPro1,1` instead of it and stay in BigSur

**Comment by ybakiame** [comment]
use [install guide](https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html) for more detials
