### ISSUE TITLE
Sucessful until i clicked Reset NVRAM.

### ISSUE THREAD

**Issue by kaioitalo** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#23]
HI, i have almost the same spec as you but with ryzen 3600 and 6900xt gpu, i managed to install hackintosh update all kexts and opencore and was everything working fine till i clicked Reset NVRAM, after that the boot on opencore post dont show the post like this:
![1_a6Bz1qAunySXdE9p8FmJUg](https://user-images.githubusercontent.com/22632427/166685356-b077cee6-7e34-465b-8e4c-c4182527595a.png)

Instead it shows like this 
![Screenshot (323)](https://user-images.githubusercontent.com/22632427/166685974-4904c2df-e912-491c-88f8-6dce1b43552b.png)

And when i click to boot the bar dont progress anymore and the system freeze or when it start progressing the system reboots,
i tryed everything i could to rollback, used old efi and kexts, others usb disks, clear cmos, i updated the bios then downgraded, used only one ram stick, nothing seems to work and the opencore post dont go back to graphic.

The install disk dont boot either or recovery.

I think i just broke my motherboard or gpu bios?! and locked macosx
Any help would be appreciated.

**Comment by ybakiame** [comment]
better read it first.[OpenCore beauty treatment](https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui)
