### ISSUE TITLE
Who could help me with Black screen (mouse works) right before installer (Radeon Rx580)

### ISSUE THREAD

**Issue by mrtiddy** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#24]
Who could help me? I have upgraded the loader and trying to install either Monterey or Ventura. With the loader, Big Sur is loading fine. Everything works. When trying to do a fresh Monterey (or Ventura) install, I get through all the messages, get tha apple logo and then I get a black screen with a working mouse pointer. Who knows how to fix this?
Help would be highly appreciated

- B550 Mag Mortar (no WIFI)
- Rx580 Radeom

**Comment by ybakiame** [comment]
> Who could help me? I have upgraded the loader and trying to install either Monterey or Ventura. With the loader, Big Sur is loading fine. Everything works. When trying to do a fresh Monterey (or Ventura) install, I get through all the messages, get tha apple logo and then I get a black screen with a working mouse pointer. Who knows how to fix this? Help would be highly appreciated
> 
>     * B550 Mag Mortar (no WIFI)
> 
>     * Rx580 Radeom

Maybe you should upgrade your BIOS version.I have encountered this problem with `7C94v12`.

**Comment by mrtiddy** [comment]
Dear yvakiame,

super thanks for your quick response. I upgraded the bios and it works like a charm now. I downgraded the bios intentionally before, because I thought it was necessary looking at the readme. Anyway, thanks for the tip!
