### ISSUE TITLE
3900x 580x MSI-B550M-MORTAR-WIFI Complete installation with ventura, but

### ISSUE THREAD

**Issue by junyddo** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#26]
3900x 580x MSI-B550M-MORTAR-WIFI Complete installation with ventura, but failed to activate sidecar function. 
It was accessible using a wired connection, but it floated a black screen.
Do you know how to operate the sidecar in this situation without black screen?

**Comment by ybakiame** [comment]
I don't have an ipad for testing, you can get help on the [amd-osx forum](https://forum.amd-osx.com/)
