### ISSUE TITLE
Wifi用不了，hackintool显示AirportItlwm未安装，有遇到过同样的问题吗

### ISSUE THREAD

**Issue by heiheihie** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#27]

**Comment by ybakiame** [comment]
1. 试试先进入`Windows`后重启再进入`macOS`
2. `Ventura`版本的驱动开机需要等待一段时间才能连接上`wifi`， [itlwm](https://github.com/OpenIntelWireless/itlwm) 已经两个月没有过提交了。如果介意的话可以回退到 `Monterey` 或 `BigSur`

**Comment by ilovemcdfries** [comment]
用最新的AirportItlwm v2.2.0 Stable 解决了Wi-Fi问题。
