### ISSUE TITLE
OC验证报错，直接写入EFI到USB会卡EB代码

### ISSUE THREAD

**Issue by 834973509** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#29]
工程师你好，
我的主板不带WIFI，型号和您一样
OC验证：
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.9.2!
Kernel->Block[0]->Identifier contains illegal character!
CheckKernel returns 1 error!
Completed validating C:/Users/83497/Desktop/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTARWIFI-master/EFI/0C/config.plist in 2 ms. Found 1 issue requiring attention.

**Comment by ilovemcdfries** [comment]
发一发您的配置 和EB代码

> OC验证：
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.9.2!
Kernel->Block[0]->Identifier contains illegal character!
CheckKernel returns 1 error!
Completed validating C:/Users/83497/Desktop/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTARWIFI-master/EFI/0C/config.plist in 2 ms. Found 1 issue requiring attention.

这个我安装的时候也有 没什么问题 你可以试试更新OC 0.9.2。

**Comment by 834973509** [comment]
已经更新到 oc0.9.2
B550 msi
AMD 7 3700x 8core
5700xt 显卡
后来在tg有一个人发给我一个不知道哪来的efi一下就进去了，但是我依然不知道为什么咱俩一样反而不能用，他给我的一下就能用了。或者我怎么把他的EFI我通过邮件发给你，能帮我检查一下为什么吗？谢谢

**Comment by ybakiame** [comment]
> 已经更新到 oc0.9.2
> B550 msi
> AMD 7 3700x 8core
> 5700xt 显卡
> 后来在tg有一个人发给我一个不知道哪来的efi一下就进去了，但是我依然不知道为什么咱俩一样反而不能用，他给我的一下就能用了。或者我怎么把他的EFI我通过邮件发给你，能帮我检查一下为什么吗？谢谢

把 `USBToolBox.kext` 和 `UTBMap.kext` 禁用了试试，如果是用的 `macrecovery` 安装的话会卡一段时间，多等会儿就好了。
