### ISSUE TITLE
Ventura上WIFI和蓝牙无法正常使用

### ISSUE THREAD

**Issue by trah01** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#30]
虽然我的主板也是MSI-B550M-MORTAR-WIFI，但是无线网卡是AX210，并非AX200，感觉是这个网卡的问题？有尝试根据[国光的教程](https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-1/)进行USB定制，但并没有起作用。BIOS版本是7C94v1D，有无办法解决WiFi和蓝牙问题，AX200的驱动和AX210是不通用的吗

**Comment by ilovemcdfries** [comment]
我蓝牙也用不了； [Wi-Fi下载最新的[[AirportItlwm_v2.2.0_stable_Ventura.kext.zip]](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0)  解决了我的 Wi-Fi问题；我用了BIOS 7C94v1E.

**Comment by trah01** [comment]
> 我蓝牙也用不了； [Wi-Fi下载最新的[[AirportItlwm_v2.2.0_stable_Ventura.kext.zip]](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0) 解决了我的 Wi-Fi问题；我用了BIOS 7C94v1E.

WIFI我昨天也更新了个kext，已经可以正常使用，现在蓝牙无法正常驱动使用

**Comment by ilovemcdfries** [comment]
@trah01 搞了好几周 我终于弄好了蓝牙；首先 照着[这个](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435)加bluetoothExternalDongleFailed 和 bluetoothInternalControllerInfo 然后 [换这里的](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/434)BluetoolFixup.kext 刷两次NVRAM； 如果还不行 拔掉PSU电源30秒-1分钟 然后蓝牙就能用了。弄完后可能会有Bug不显示右上蓝牙和WI-FI， 重起电脑就好了。

**Comment by trah01** [comment]
> @trah01 搞了好几周 我终于弄好了蓝牙；首先 照着[这个](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435)加bluetoothExternalDongleFailed 和 bluetoothInternalControllerInfo 然后 [换这里的](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/434)BluetoolFixup.kext 刷两次NVRAM； 如果还不行 拔掉PSU电源30秒-1分钟 然后蓝牙就能用了。弄完后可能会有Bug不显示右上蓝牙和WI-FI， 重起电脑就好了。

首先，谢谢你的帮助，但我已经把显卡换成了RX6800XT，貌似该显卡在Ventura上并没有免驱？或者我设置不对？并没有成功的进入到系统，所以无法验证你的方案是否有效，很抱歉，但很谢谢你给我提供的帮助

**Comment by ybakiame** [comment]
已经替换了修补版本的 `BlueToolFixup.kext` 现在蓝牙可以正常工作了。
