### ISSUE TITLE
蓝牙依旧没有对我起作用

### ISSUE THREAD

**Issue by trah01** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#31]
已经更新为最新的EFI，虽然按照该[问题](https://github.com/ybakiame/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI/issues/30)中[ilovemcdfries](https://github.com/ilovemcdfries)提供的方法进行操作，但很可惜并没有奏效。不知道是否是AX210网卡未被支持，同时，附上我的[EFI](https://github.com/trah01/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI-for-trah.git)，也许是我的配置有误导致的？

**Comment by ybakiame** [comment]
> 已经更新为最新的EFI，虽然按照该[问题](https://github.com/ybakiame/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI/issues/30)中[ilovemcdfries](https://github.com/ilovemcdfries)提供的方法进行操作，但很可惜并没有奏效。不知道是否是AX210网卡未被支持，同时，附上我的[EFI](https://github.com/trah01/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI-for-trah.git)，也许是我的配置有误导致的？

只需要打过补丁的 `BlueToolFixup.kext` 就行了其他不用改。 ax210 按理来说应该是没问题的。保证在windows有蓝牙，然后热重启到macos试试，不行先重制 nvram 再看看。

**Comment by trah01** [comment]
> > 已经更新为最新的EFI，虽然按照该[问题](https://github.com/ybakiame/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI/issues/30)中[ilovemcdfries](https://github.com/ilovemcdfries)提供的方法进行操作，但很可惜并没有奏效。不知道是否是AX210网卡未被支持，同时，附上我的[EFI](https://github.com/trah01/Ryzen-Hackintosh-OpenCore-MSI-B550M-MORTAR-WIFI-for-trah.git)，也许是我的配置有误导致的？
> 
> 只需要打过补丁的 `BlueToolFixup.kext` 就行了其他不用改。 ax210 按理来说应该是没问题的。保证在windows有蓝牙，然后热重启到macos试试，不行先重制 nvram 再看看。

是我的问题，没有安装到IntelBTpatch那个，添加进去后解决了问题，浪费作者时间了，抱歉
