### ISSUE TITLE
关于处理器型号显示未知

### ISSUE THREAD

**Issue by cncqla** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#32]
你好，我使用了这个引导文件，配置是3600x的处理器，但是处理器显示未知，问一下，你图片中显示型号是怎么更改的，或者说processorType这个值去哪里查询对应的CPU呢？

**Comment by ybakiame** [comment]
> 你好，我使用了这个引导文件，配置是3600x的处理器，但是处理器显示未知，问一下，你图片中显示型号是怎么更改的，或者说processorType这个值去哪里查询对应的CPU呢？

用的 [RestrictEvents](https://github.com/acidanthera/RestrictEvents) 你把引导参数里面的 `revcpu=1` 关了试试

**Comment by cncqla** [comment]
> > 你好，我使用了这个引导文件，配置是3600x的处理器，但是处理器显示未知，问一下，你图片中显示型号是怎么更改的，或者说processorType这个值去哪里查询对应的CPU呢？
> 
> 用的 [RestrictEvents](https://github.com/acidanthera/RestrictEvents) 你把引导参数里面的 `revcpu=1` 关了试试

好的，我试试，感谢！
