### ISSUE TITLE
感谢EFI，请问CPU和内存频率读取不正确如何修改呀？

### ISSUE THREAD

**Issue by huahuacn** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#4]
如题，我CPU是5600X，机型选的是MAC7,1。
CPU不能和你一样显示CPU型号。RestrictEvents.kext 是1.02版本。
系统是11.4 beta2。
然后内存我是3600的，读取到的是2667。
还有就是桌面上方的音量调节是灰色的。
请问你知道这些问题如何解决吗？
感谢。

**Comment by ybakiame** [comment]
> 如题，我CPU是5600X，发行选择的是MAC7,1。CPU
> 不能和你一样显示CPU型号。RestrictEvents.kext是1.02版本。
> 系统是11.4 beta2。
> 然后内存我是3600的，读取到的是2667。 。
> 还有就是桌面上方的音量调节是灰色的。
> 请问你知道这些问题如何解决吗？
> 感谢。

---
> 内存：参考[Mac Pro7,1内存错误](https://dortania.github.io/OpenCore-Post-Install/universal/memory.html#mapping-our-memory)
> 机型问题：机型是显示unknow还是因特尔的？[issues](https://github.com/acidanthera/bugtracker/issues/1625)和[amd-osx](https://forum.amd-osx.com/index.php?threads/fix-cpu-name-with-restrictevents.1736/)可能会有帮助
> 音量无法调节：检查applealc是否正常工作？是否选择了正确的输出设备

**Comment by huahuacn** [comment]
CPU显示的未知。
我不能改成MAC1,1，因为我的显卡是AMD 6800，我必须选择MAC PRO 7,1 才能进入系统。
音量按钮是灰色的，声音都是正常的，就是在桌面右上那里无法快捷调整。

**Comment by huahuacn** [comment]
CPU的问题已经解决，将ProcessorType改成1537，就正常显示了，内存和音量调节还没找到原因。。。

**Comment by huahuacn** [comment]
<img width="561" alt="QQ20210508-215448@2x" src="https://user-images.githubusercontent.com/31203217/117541778-08ff1200-b048-11eb-867b-6cb0dee194db.png">

内存的问题我也解决好了。
现在就是音量调节不了的问题。
我发现在控制面板里面也无法调整音量。
但是声音输出是正常的。
请问你知道可能是什么原因吗？

---
> DP和HDMI外接的显示器音量好像调不了，可以试试[MonitorControl](https://github.com/MonitorControl/MonitorControl)。用耳机的时候能不能调节？

**Comment by echokk11** [comment]
内存如何解决的分享下呗

**Comment by mythgp** [comment]
内存如何解决的分享下呗

**Comment by mythgp** [comment]
> <img alt="QQ20210508-215448@2x" width="561" src="https://user-images.githubusercontent.com/31203217/117541778-08ff1200-b048-11eb-867b-6cb0dee194db.png">
> 
> 内存的问题我也解决好了。 现在就是音量调节不了的问题。 我发现在控制面板里面也无法调整音量。 但是声音输出是正常的。 请问你知道可能是什么原因吗？
> 
> > DP和HDMI外接的显示器音量好像调不了，可以试试[MonitorControl](https://github.com/MonitorControl/MonitorControl)。用耳机的时候能不能调节？

内存如何解决的分享下呗
