### ISSUE TITLE
感谢提供EFI，不过usb2.0口和type旁边的usb3.1口都不能正常使用

### ISSUE THREAD

**Issue by gzrainfeng** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#5]
你好，我也是用微星B550m（wifi）的主板，用了大哥你的efi后测试只有2个usb3.1口能正常使用其他口都不能用，希望下个版本能修复这问题，对了我的cpu是5800x这个应该影响不大吧，在此十分感谢大哥提供的EFI文件

**Comment by ybakiame** [comment]
> 你好，我也是用微星B550m（wifi）的主板，用了大哥你的efi后测试只有2个usb3.1口能正常使用其他口都不能用，希望下一个版本能修复这问题，对了我的cpu是5800x这个应该影响不大吧，在此十分感谢大哥提供的EFI文件

---
> 用Hackintool查看一下设备插入usb端口时有没有反应，使用[脚本](https://github.com/corpnewt/USBMap)或其他工具进行usb映射。

**Comment by gzrainfeng** [comment]
我用hackintool查看有1个usb口有反应，但是不知道用什么工具进行映射，还是请问大哥你用什么版本的bios，如果你usb口都正常理论上应该我的也正常的，我刷成和你相同版本的主板bios就应该可以了

**Comment by ybakiame** [comment]
> 我用hackintool查看有1个usb口有反应，但是不知道用什么工具进行映射，还是请问大哥你用什么版本的bios，如果你usb口都正常理论上应该我的也正常的，我刷成和你相同版本的主板bios就应该可以了

---
> MSI Dragon Center升的最新版

**Comment by gzrainfeng** [comment]
感谢，我升级最新版后所有usb口都能正常用了
