### ISSUE TITLE
谢谢一直更新EFI！声卡音频存在问题！

### ISSUE THREAD

**Issue by Xboxpig** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#7]
layout注入11，系统内能识别到声卡，外置音响有时候启动系统之后会有声音，大多数时候没有声音。
![Uploading 124C92E5-EB34-41AA-B63E-2405AC6D8D96.png…]()

**Comment by ybakiame** [comment]
> 没遇到过，试试其他的layout id 或者 [AppleALC定制 ](https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html)

**Comment by ybakiame** [comment]
> 布局注入11，系统内能识别声卡，外置硬盘驱动启动系统之后会响起，几乎没有声音。

是否在windows下升级了声卡驱动？
是的话卸载掉声卡驱动。

**Comment by Xboxpig** [comment]
是的，冷启动Windows后再重启到MAC，问题就会出现；直接冷启动MAC则没有这个问题。
还是想请教一下是什么驱动的原因导致的
