### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by strong0018** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#8]
MAG-MSI--B550M-MORTAR-（没有wifi）的主板+5600X+RX580

用了你的这个EFI之后，一开始卡EB，更新了CPU核心参数之后正常引导。装完系统之后声卡没声音，看声音信息里输入和输出设备都已经识别，但是就是没有任何声音。尝试过更换aclid无效，DP接口声音正常但是没有音量调节。

**Comment by ybakiame** [comment]
> MAG-MSI--B550M-MORTAR-（没有wifi）的主板+5600X+RX580
> 
> 用了你的这个EFI之后，一开始卡EB，更新了CPU核心参数之后正常引导。装完系统之后声卡没声音，看声音信息里输入和输出设备都已经识别，但是就是没有任何声音。尝试过更换aclid无效，DP接口声音正常但是没有音量调节。

如果在windows下升级了声卡驱动applealc就会失效(还没有找到解决办法)
音量、显示器调节可以用[MonitorControl](https://github.com/MonitorControl/MonitorControl)

**Comment by strong0018** [comment]
是的，我也发现了这个问题，不过我是在安装黑苹果之前就装好了Windows下的声卡驱动，不知道为什么这样还有影响。卸载官方驱动让Windows自己识别并安装一个默认驱动就OK了，猜测可能官方驱动或其组件在nvram里写入了某些东西导致applealc无法正常使用。

**Comment by Xboxpig** [comment]
冷启动Windows后再重启到MAC，问题就会出现；直接冷启动MAC则没有这个问题

**Comment by lwj1994** [comment]
big sur 可以用这个 efi吗？

**Comment by strong0018** [comment]
可以，我就是big sur，要定制一下USB

**Comment by lwj1994** [comment]
@strong0018 我没定制 直接刷了。好像没啥问题。但是 wifi 和蓝牙有点问题
wifi: 刚进系统时，引导页输入wifi密码后按回车一直在转圈，关闭wifi再打开wifi后要等一段时间后才会自动重连
蓝牙：无法关闭

**Comment by strong0018** [comment]
我是博通的免驱卡，如果你是Intel的无线网卡，需要去下载最新的Intel WiFi驱动和蓝牙驱动

**Comment by lwj1994** [comment]
我把笔记本完全迁移到黑苹果后，蓝牙无法使用了。😿 一直是关闭状态，找不到蓝牙设备了。

**Comment by lwj1994** [comment]
重新安装蓝牙设备也找不到了😢

**Comment by lwj1994** [comment]
@strong0018  你们的隔空投送好使吗？

**Comment by strong0018** [comment]
博通免驱卡所有功能都正常，投送，接力都和白果一样

**Comment by lwj1994** [comment]
我发现装完黑苹果后，蓝牙隔一段就是就会丢了。需要在 bios 中把 wifi module 禁止再打开，搜了下貌似是这块主板的问题，不知道在 windows 端更新驱动能不能解决。

**Comment by ybakiame** [comment]
> 我发现装完黑苹果后，蓝牙一段就会丢了。需要在bios中把wifi模块禁止再打开，搜了下貌似是这块主板的问题，不知道在windows端更新驱动能不能解决。

确实这块板子有这个问题，无论是windows还是mac。多用一段时间会好一些

**Comment by lwj1994** [comment]
我的cpu 5600x 在关于本机里没有正确识别（显示未知），用网上的方法在 bigsur 下没办法修改系统的文件。不知有什么方法可以正确显示

**Comment by ybakiame** [comment]
> 我的cpu 5600x 在关于本机里没有正确识别（显示未知），用网上的方法在 bigsur 下没办法修改系统的文件。不知有什么方法可以正确显示

> [参考](https://github.com/ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI-EFI/issues/4#issuecomment-835363762)

**Comment by lwj1994** [comment]
wifi 偶尔会突然没网了，wifi 关了再开就好了。你们有这种情况吗？b550 自带的网卡

**Comment by strong0018** [comment]
> wifi 偶尔会突然没网了，wifi 关了再开就好了。你们有这种情况吗？b550 自带的网卡

你上面不是说过了吗？这个应该是你板子的问题，想解决的话就换个苹果拆机卡
