### ISSUE TITLE
唤醒后系统卡顿

### ISSUE THREAD

**Issue by strong0018** [ybakime/Hackintosh-Opencore-MAG-MSI--B550M-MORTAR-WIFI#9]
最近发现睡眠时间一长，唤醒后系统就变得非常卡，那种感觉就像Windows后台运行着一个高负载的应用，所有的系统响应都非常慢，而且有时还会出现APP崩溃的情况。查看后台也没有占用CPU特别高的进程

**Comment by ybakiame** [comment]
在我使用bigsur期间并没有遇到过这种情况，你可以前往[AMD-OSX](https://forum.amd-osx.com/index.php?forums/11-00-big-sur.32/)寻求帮助，并提供对应的信息

**Comment by ybakiame** [comment]
> 最近一个发现睡眠时间一长，一觉醒来后系统就变得非常卡，就好像Windows后台运行着高负载的应用，所有的系统响应都非常缓慢，而且有时会出现APP崩溃的情况。后台也没有占用CPU特别高的进程

可以试试降低BIOS版本
